version: '3.7'

services:
    influxdb:
        image: influxdb:2.5-alpine
        volumes:
            - influxdb2-data:/var/lib/influxdb2:rw
            - ./influxdb-backups:/home/influxdb/backups
            - ./docker-scripts:/home/influxdb/scripts
        ports:
            - "8086:8086"
        env_file:
            - ./influxdb.env

    grafana:
        image: grafana/grafana:9.2.6
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
            - grafana-data:/var/lib/grafana
        env_file:
            - ./grafana.env

volumes:
    grafana-data:
    influxdb2-data: