version: '3.7'

services:
    influxdb:
        image: influxdb:2.5-alpine
        volumes:
            - influxdb2-data:/var/lib/influxdb2:rw
        ports:
            - "8086:8086"
        environment:
            - ./influx2.env

    # Use the influx cli to set up an influxdb instance.
    influxdb_cli:
        links:
            - influxdb
        image: influxdb:2.5-alpine
        volumes:
            # Mount for influxdb data directory and configuration
 #            - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
 #            - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
            - ./influxdb2:/var/lib/influxdb2:rw
        environment:
            # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
            - DOCKER_INFLUXDB_INIT_ORG=home
            - DOCKER_INFLUXDB_INIT_BUCKET=energy
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
#            - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
#            - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
        entrypoint: ["./entrypoint.sh"]
        restart: on-failure:10
        depends_on:
            - influxdb
#
#     telegraf:
#         image: telegraf
#         links:
#             - influxdb
# #         volumes:
#             # Mount for telegraf config
# #             - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
# #         env_file:
# #             - ./influxv2.env
#         environment:
#             - DOCKER_INFLUXDB_INIT_ORG=myorg
#             - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
#             - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
#         depends_on:
#             - influxdb_cli

    grafana:
        image: grafana/grafana:9.2.6
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - grafana-data:/var/lib/grafana
        environment:
            - ./grafana.env

volumes:
    grafana-data:
    influxdb2-data: