apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database should be mapped to a bucket
    database: db0
    jsonData:
        httpMode: GET
#         httpHeaderName1: 'Authorization'
#     secureJsonData:
#         httpHeaderValue1: 'Token <token>'

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: db0
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: true
    editable: true