apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database should be mapped to a bucket
    database: energy
    jsonData:
        httpMode: GET
        httpHeaderName1: 'Authorization'
    secureJsonData:
        httpHeaderValue1: '-mJVxHfZSyCiI8PdW-4usF8PebiExZ2lQLPBfjS2d__255VaMCDVZEVOMzOGULlvqhVLNF9F3_3e28CXWMaP-g=='

#   - name: InfluxDB
#     type: influxdb
#     access: proxy
#     database: db0
#     user: admin
#     password: admin
#     url: http://influxdb:8086
#     isDefault: true
#     editable: false