apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: energy
    jsonData:
        httpMode: GET
        httpHeaderName1: 'Authorization'
    secureJsonData:
        httpHeaderValue1: 'Token influx-db-token'

  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 'influx-db-token'
    jsonData:
      version: Flux
      organization: home
      defaultBucket: energy
      tlsSkipVerify: true