{
 "title": "Energy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"active_power\")"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"active_power\")"
    },
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"reactive_power\")"
    },
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"apparent_power\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"voltage\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"current\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"frequency\")"
    }
   ]
  },
  {
   "title": "Power Factory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"power_factory\")"
    }
   ]
  }
 ]
}